# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 41401
  servlet:
    context-path: /
    session:
      timeout: 3600s

spring:
#  profiles:
#    active: @active@
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #  servlet:
  #    multipart:
  #      max-file-size: 100MB
  #      max-request-size: 100MB
  #      enabled: true
  #  freemarker:
  #    suffix: .html
  #    request-context-attribute: request
  http:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
  transaction:
    rollback-on-commit-failure: true
#  security:
#    user:
#      name: guest
#      password: qhzhang
#      roles: VIP1


logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.mvc: DEBUG
    com: DEBUG


